export const QUIZ_CATEGORIES = [
  'General Knowledge',
  'Science',
  'Mathematics',
  'History',
  'Geography',
  'Sports',
  'Music',
  'Movies',
  'Literature',
  'Technology',
  'Art',
  'Politics',
  'Business',
  'Nature',
  'Food & Drink',
  'Religion',
  'Language',
  'Space',
  'Computers',
  'Animals',
  'TV & Entertainment',
];
