export const RANDOM_FACTS = [
  "The shortest war in history was between Britain and Zanzibar in 1896. Zanzibar surrendered after 38 minutes.",
  "A group of flamingos is called a 'flamboyance'.",
  "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.",
  "Octopuses have three hearts and blue blood.",
  "Seriously, still deciding? My grandma could make up her mind faster!",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
  "Bananas are berries, but strawberries aren't.",
  "A single cloud can weigh more than a million pounds.",
  "The inventor of the Frisbee was turned into a Frisbee after he died.",
  "You're a confused individual. Like a GPS that keeps saying 'recalculating'...",
  "Venus is the only planet that rotates clockwise.",
  "The dot over the letter 'i' is called a tittle.",
  "A jiffy is an actual unit of time: 1/100th of a second.",
  "My facts are ending... just like your indecision!",
  "The longest time between two twins being born is 87 days.",
  "Wombat poop is cube-shaped.",
  "The total weight of all ants on Earth is about equal to the weight of all humans.",
  "Cows have best friends and get stressed when separated.",
  "The first computer mouse was made of wood.",
  "Are you still here? I'm starting to doubt your decision-making skills...",
  "A day on Venus is longer than a year on Venus.",
  "The first recorded game of baseball was played in 1846 in Hoboken, New Jersey.",
  "The unicorn is the national animal of Scotland.",
  "The longest English word without a vowel is 'rhythms'.",
  "I could have learned a new language by now while waiting for you to decide...",
  "The Great Wall of China is not visible from space with the naked eye.",
  "A shrimp's heart is in its head.",
  "The first product to have a barcode was Wrigley's gum.",
  "The opposite sides of a dice always add up to seven.",
  "You do realize this is getting awkward, right? Still no decision?",
  "Cleopatra lived closer in time to the moon landing than to the building of the Great Pyramid.",
  "The longest English word is 189,819 letters long (it's the chemical name for titin).",
  "A bolt of lightning is five times hotter than the sun's surface.",
  "The longest hiccuping spree lasted 68 years.",
  "I'm starting to think you enjoy reading facts more than playing...",
  "The first oranges weren't orange - they were green.",
  "The '@' symbol has no official name in English.",
  "The human nose can detect about 1 trillion different smells.",
  "The world's oldest piece of chewing gum is over 9,000 years old.",
  "Okay, now you're just messing with me. Play already!",
  "The first alarm clock could only ring at 4 AM.",
  "A day on Mercury is twice as long as its year.",
  "The longest wedding veil was longer than 63 football fields.",
  "The first YouTube video was uploaded in 2005 and was 18 seconds long.",
  "The word 'nerd' was first coined by Dr. Seuss.",
  "The longest English word with all letters in alphabetical order is 'almost'.",
  "The first product to feature a barcode was a pack of Wrigley's chewing gum.",
  "The longest time between two twins being born is 87 days.",
  "The world's quietest room is so quiet you can hear your own organs.",
  "The human body contains enough fat to make seven bars of soap.",
  "The longest English word without a vowel is 'rhythms'.",
  "The first computer bug was an actual insect (a moth stuck in a relay).",
  "The first recorded game of baseball was played in 1846 in Hoboken, New Jersey.",
  "The unicorn is the national animal of Scotland.",
  "The longest hiccuping spree lasted 68 years.",
  "The first oranges weren't orange - they were green.",
  "The '@' symbol has no official name in English.",
  "The human nose can detect about 1 trillion different smells.",
  "The world's oldest piece of chewing gum is over 9,000 years old.",
  "The first alarm clock could only ring at 4 AM.",
  "A day on Mercury is twice as long as its year.",
  "The longest wedding veil was longer than 63 football fields.",
  "The first YouTube video was uploaded in 2005 and was 18 seconds long.",
  "The word 'nerd' was first coined by Dr. Seuss.",
  "The longest English word with all letters in alphabetical order is 'almost'.",
  "The first product to feature a barcode was a pack of Wrigley's chewing gum.",
  "The longest time between two twins being born is 87 days.",
  "The world's quietest room is so quiet you can hear your own organs.",
  "The human body contains enough fat to make seven bars of soap.",
  "The longest English word without a vowel is 'rhythms'.",
  "The first computer bug was an actual insect (a moth stuck in a relay).",
  "The first recorded game of baseball was played in 1846 in Hoboken, New Jersey.",
  "The unicorn is the national animal of Scotland.",
  "The longest hiccuping spree lasted 68 years.",
  "The first oranges weren't orange - they were green.",
  "The '@' symbol has no official name in English.",
  "The human nose can detect about 1 trillion different smells.",
  "The world's oldest piece of chewing gum is over 9,000 years old.",
  "The first alarm clock could only ring at 4 AM.",
  "A day on Mercury is twice as long as its year.",
  "The longest wedding veil was longer than 63 football fields.",
  "The first YouTube video was uploaded in 2005 and was 18 seconds long.",
  "The word 'nerd' was first coined by Dr. Seuss.",
  "The longest English word with all letters in alphabetical order is 'almost'.",
  "The first product to feature a barcode was a pack of Wrigley's chewing gum.",
  "The longest time between two twins being born is 87 days.",
  "The world's quietest room is so quiet you can hear your own organs.",
  "The human body contains enough fat to make seven bars of soap.",
  "The longest English word without a vowel is 'rhythms'.",
  "The first computer bug was an actual insect (a moth stuck in a relay).",
  "The first recorded game of baseball was played in 1846 in Hoboken, New Jersey.",
  "The unicorn is the national animal of Scotland.",
  "The longest hiccuping spree lasted 68 years.",
  "The first oranges weren't orange - they were green.",
  "The '@' symbol has no official name in English.",
  "The human nose can detect about 1 trillion different smells.",
  "The world's oldest piece of chewing gum is over 9,000 years old.",
  "The first alarm clock could only ring at 4 AM.",
  "A day on Mercury is twice as long as its year.",
  "The longest wedding veil was longer than 63 football fields.",
  "The first YouTube video was uploaded in 2005 and was 18 seconds long.",
  "The word 'nerd' was first coined by Dr. Seuss.",
  "The longest English word with all letters in alphabetical order is 'almost'."
];

// Indexes where interjection messages appear:
// 4: "Seriously, still deciding? My grandma could make up her mind faster!"
// 9: "You're a confused individual. Like a GPS that keeps saying 'recalculating'..."
// 13: "My facts are ending... just like your indecision!"
// 19: "Are you still here? I'm starting to doubt your decision-making skills..."
// 24: "I could have learned a new language by now while waiting for you to decide..."
// 29: "You do realize this is getting awkward, right? Still no decision?"
// 34: "I'm starting to think you enjoy reading facts more than playing..."
// 39: "Okay, now you're just messing with me. Play already!"